### ISSUE TITLE
"window" is not available during server side rendering.

### ISSUE THREAD

**Issue by dddieon** [react-sprint/gatsby-blog-starter-with-typescript#22]
## Toggler.tsx  /  Header.tsx 

window 객체의 localstorage나 matchMedia를 사용하고 있습니다만
`"window" is not available during server side rendering.`에러로 빌드가 안되고 있습니다
하단 링크들을 참고해서 수정해야 할 듯 합니다

[한글]
https://www.sungikchoi.com/blog/window-is-not-available/
[공식]
https://www.gatsbyjs.com/docs/debugging-html-builds/#how-to-check-if-window-is-defined

**Comment by sungyun6789** [comment]
window...
아마 대부분 제가 쓴 거 같은데 주말까지 수정해서 푸쉬 하겠습니다

**Comment by jeongshin** [comment]
확인해서 다시 pr 올렸습니다. 
이슈 알려주셔서 감사합니다 🙇🏻‍♂️
